apiVersion: seed.ibm.com/v1
kind: Function
metadata:
  name: en2shakespeare
  namespace: ${projectName}
spec:
  packages:
  - name: ${projectName}
    actions:
    - codeUri: https://rawgit.com/kerryspchang/translation-demo/master/lib/en2shakespeare.js
      runtime: "nodejs:6"
      parameters:
      - name: mysecret.ftApiKey:
        type: string
        value: 128

---
apiVersion: seed.ibm.com/v1
kind: CloudService
metadata:
  name: mytranslator
  namespace: ${projectName}
spec:
  service: language_translator
  plan: lite
---
apiVersion: seed.ibm.com/v1
kind: Function
metadata:
  name: watson-language
  namespace: ${projectName}
spec:
  packages:
  - bind:  /whisk.system/watson-translator
    service: mytranslator
